[font]
normal = { family = "Comic Code", style = "Regular" }
bold = { family = "Comic Code", style = "Bold" }
italic = { family = "Comic Code", style = "Italic" }
bold_italic = { family = "Comic Code", style = "Bold Italic" }
size = 10.0
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
builtin_box_drawing = true
